# pipeline for projec
# react + vite frontent
#built on windoews

name: CI Build

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]
    types: [ "opened", "synchronize", "reopened" ]
  workflow_dispatch:
    inputs:
      build-type:
        description: 'Type of build'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - production
      run-tests:
        description: 'Run tests'
        required: true
        default: true
        type: boolean
      notify:
        description: 'Notify team'
        required: false
        default: false
        type: boolean
      deploy-frontend:
        description: 'Deploy frontend'
        required: false
        default: false
        type: boolean
      deploy-backend:
        description: 'Deploy backend'
        required: false
        default: false
        type: boolean  
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - development
          - production
      version:
        description: 'Version to deploy'
        required: true
        default: 'lastest'
        type: string

env:
  NODE_VERSION: '20'
  JAVA_VERsion: '24'    
  BUILD_TYPE: ${{ github.event.inputs.build-type || 'development' }}    

jobs:
  frontend:
    name: Frontend CI/CD
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install frontend dependencies
        run: npm install
      
      - name: Build project
        run: npm run build
        env: 
          NODE_ENV: ${{ env.BUILD_TYPE }}

      
      - name: Run tests
        if: ${{ github.event.inputs['run-tests'] == 'true' }}
        run: npm test
      
      - name: Notify team
        run: echo "Notifying team..."
      
      - name: Deploy application
        run: |
          echo "Deploying version ${{ github.event.inputs['version'] }} to ${{ github.event.inputs['environment'] }} environment"
          # Add your deployment script/commands here
