# Name of the workflow as it appears in the Actions tab
name: CI Build

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches: [ "main" ]

# Define the jobs to run in the workflow
jobs:
  # The name of the job
  build:
    # The type of machine to run the job on
    runs-on: ubuntu-latest
    
    # Sequence of tasks executed within the job
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify the version of Node.js
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
      
      # Step 4: Build the project
      - name: Build project
        run: npm run build
